"""added followers table

Revision ID: 938320e39b21
Revises: 37efe84aa9bc
Create Date: 2020-04-01 13:30:37.930069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938320e39b21'
down_revision = '37efe84aa9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
